# Generated by Django 3.2 on 2022-07-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_imagerelated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerelated',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='关联的模型'),
        ),
    ]
